In [16]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 705.33it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\LOQ\Downloads\archive (5)\all_tickets.csv")

In [2]:
df.head()

,title,body,ticket_type,category,sub_category1,sub_category2,business_service,urgency,impact
0,NaN,hi since recruiter lead permission approve req...,1,4,2,21,71,3,4
1,connection with icon,icon dear please setup icon per icon engineers...,1,6,22,7,26,3,4
2,work experience user,work experience user hi work experience studen...,1,5,13,7,32,3,4
3,requesting for meeting,requesting meeting hi please help follow equip...,1,5,13,7,32,3,4
4,reset passwords for external accounts,re expire days hi ask help update passwords co...,1,4,2,76,4,3,4

In [3]:
df.isna().sum()

title               712
body                  0
ticket_type           0
category              0
sub_category1         0
sub_category2         0
business_service      0
urgency               0
impact                0
dtype: int64

In [4]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")
emb = model.encode("This is a test")
print(len(emb))

c:\Users\LOQ\anaconda3\envs\tf_final\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 829.59it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

384

In [5]:
temp = df.iloc[:5000,:]

In [6]:
temp.head()

,title,body,ticket_type,category,sub_category1,sub_category2,business_service,urgency,impact
0,NaN,hi since recruiter lead permission approve req...,1,4,2,21,71,3,4
1,connection with icon,icon dear please setup icon per icon engineers...,1,6,22,7,26,3,4
2,work experience user,work experience user hi work experience studen...,1,5,13,7,32,3,4
3,requesting for meeting,requesting meeting hi please help follow equip...,1,5,13,7,32,3,4
4,reset passwords for external accounts,re expire days hi ask help update passwords co...,1,4,2,76,4,3,4

In [22]:
temp["vector"] = temp['issue_description'].apply(lambda text:model.encode(text))

C:\Users\LOQ\AppData\Local\Temp\ipykernel_2000\239352504.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["vector"] = temp['issue_description'].apply(lambda text:model.encode(text))

In [23]:
temp

,ticket_id,customer_name,customer_email,product,category,issue_description,resolution_notes,priority,status,channel,...,escalated,sla_breached,operating_system,browser,payment_method,language,preferred_contact_time,issue_complexity_score,customer_segment,vector
0,1,Patricia Smith,patricia.smith760@outlook.com,Web Portal,Account Suspension,The payment was deducted from my bank account ...,Data synchronization restored after backend se...,Urgent,Open,Email,...,No,Yes,MacOS,Edge,PayPal,French,Afternoon,4,Small Business,"[0.04464159, 0.016413702, 0.028579671, -0.0315..."
1,2,Patricia Williams,patricia.williams390@gmail.com,Mobile App,Performance Issue,I found a bug in the latest update affecting r...,Provided step-by-step troubleshooting instruct...,Urgent,Closed,Email,...,Yes,Yes,Windows,Firefox,PayPal,English,Afternoon,2,Small Business,"[-0.042983465, 0.010400937, -0.05835836, 0.096..."
2,3,William Anderson,william.anderson651@outlook.com,Web Portal,Performance Issue,The application crashes whenever I try to uplo...,Provided step-by-step troubleshooting instruct...,Medium,Closed,Chat,...,Yes,Yes,Windows,Safari,Bank Transfer,French,Morning,4,Corporate,"[0.035143226, -0.0122245895, -0.0075532086, -0..."
3,4,David Miller,david.miller672@icloud.com,Payment Gateway,Subscription Cancellation,My subscription was cancelled without my reque...,Provided step-by-step troubleshooting instruct...,Medium,Closed,Social Media,...,Yes,No,Windows,Chrome,Credit Card,Spanish,Afternoon,7,Corporate,"[-0.020815728, -0.039034598, -0.019802377, -0...."
4,5,Robert Gonzalez,robert.gonzalez391@hotmail.com,Web Portal,Feature Request,The system is not syncing data across devices ...,We have reset the account credentials and advi...,High,Pending Customer,Email,...,Yes,No,Linux,NaN,Debit Card,Spanish,Evening,3,Corporate,"[0.04788562, -0.08118233, 0.014455154, -0.0765..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,Joseph Smith,joseph.smith61@company.com,Analytics Dashboard,Bug Report,The system is not syncing data across devices ...,Payment gateway timeout issue fixed and monito...,High,Resolved,Email,...,No,No,iOS,Edge,Bank Transfer,German,Afternoon,8,Individual,"[0.04788562, -0.08118233, 0.014455154, -0.0765..."
4996,4997,Jennifer Gonzalez,jennifer.gonzalez389@yahoo.com,Subscription Service,Account Suspension,I would like to request a refund for the recen...,Payment gateway timeout issue fixed and monito...,High,Resolved,Phone,...,No,Yes,Windows,Edge,PayPal,Japanese,Night,8,Small Business,"[-0.060798198, 0.03468921, 0.04043597, -0.0040..."
4997,4998,Sarah Rodriguez,sarah.rodriguez361@gmail.com,Cloud Storage,Payment Problem,The application crashes whenever I try to uplo...,Security settings updated and customer notifie...,Urgent,Closed,Email,...,Yes,Yes,MacOS,Edge,Crypto,English,Night,9,Small Business,"[0.035143226, -0.0122245895, -0.0075532086, -0..."
4998,4999,John Martin,john.martin601@icloud.com,Subscription Service,Performance Issue,I would like to request a refund for the recen...,Provided step-by-step troubleshooting instruct...,High,Resolved,Chat,...,No,No,Windows,Edge,Bank Transfer,Japanese,Evening,6,Corporate,"[-0.060798198, 0.03468921, 0.04043597, -0.0040..."
4999,5000,John Anderson,john.anderson285@yahoo.com,Billing System,Performance Issue,I would like to request a refund for the recen...,The issue was escalated to engineering and res...,Medium,Resolved,Phone,...,Yes,No,MacOS,Safari,Debit Card,French,Evening,9,Individual,"[-0.060798198, 0.03468921, 0.04043597, -0.0040..."

In [7]:
embeddings = model.encode(temp['body'])

In [8]:
embeddings.shape

(5000, 384)

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['category'] = encoder.fit_transform(df['category'])

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(
    embeddings, temp['category'], test_size=0.2
)

model_ml = LogisticRegression()

model_ml.fit(X_train, y_train)

LogisticRegression()

In [11]:
y_pred = model_ml.predict(X_test)

In [12]:
from sklearn.metrics import classification_report
report = classification_report(y_test,y_pred)

c:\Users\LOQ\anaconda3\envs\tf_final\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LOQ\anaconda3\envs\tf_final\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LOQ\anaconda3\envs\tf_final\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [13]:
print(report)

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           4       0.86      0.94      0.90       691
           5       0.80      0.78      0.79       221
           6       0.62      0.17      0.27        59
           7       0.67      0.36      0.47        22
           8       0.00      0.00      0.00         2
          11       0.00      0.00      0.00         4

    accuracy                           0.84      1000
   macro avg       0.42      0.32      0.35      1000
weighted avg       0.82      0.84      0.82      1000